### ISSUE TITLE
Testcomplete plugin not working Jenkins version 2.530

### ISSUE THREAD

**Issue by Ancybaby** [jenkins-infra/plugin-health-scoring#733]
### Description of the bug

Hi ,

TestComplete plugin latest version 2.1 - https://plugins.jenkins.io/TestComplete/ doesnt work with Jenkins version 2.530 . Please find the jenkins job's console output below:

Pipeline] End of Pipeline
java.lang.ClassNotFoundException: hudson.util.IOException2
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:70)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
Also: org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: adedaec3-7749-4405-8add-605003cd4abd
Caused: java.lang.NoClassDefFoundError: hudson/util/IOException2
at PluginClassLoader for cygpath//hudson.plugins.cygpath.CygpathLauncherDecorator$1.getCygpathExe(CygpathLauncherDecorator.java:104)

Can you please help on this issue?

Thanks,
Ancy

**Comment by alecharp** [comment]
Why did you create this issue here? This has nothing to do with the Plugin Health Scoring project.
